# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
appendCommitMessageToRunName:


pool:
  vmImage: 'windows-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'  # Specify your desired Python version

- script: |
    pip install virtualenv
    virtualenv venv
    .\venv\Scripts\activate
    python setup.py install
    pip install git+https://github.com/AnanyaT/Pipeline/tree/main/LithiumPackage.git
  displayName: 'Install Python dependencies'

- script: |
    .\venv\Scripts\activate
    python -m LithiumPackage.src.litihumDBFinal.py
  displayName: 'Run Python script'


